### ISSUE TITLE
FROST Extensions

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#11]
This Epic will track any extensions in functionality not currently included in the IETF draft

## Tasks

- [x] Implement message serialization
- [ ] Implement DKG
- [ ] Implement ability for any signing participant to act as an aggregator 
- [ ] Share redistribution- allow t signers to add/remove new members and ratchet forward the secret for forward secrecy

**Comment by dconnolly** [comment]
All tasks either done or opened in issues
