### ISSUE TITLE
Epic: Improvements from FROST Audit

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#451]
## Motivation

We want to ensure that we track and act upon findings from the audit. 

### `frost-core`

- [x] #442
    - fixed in #452 
- [x] #443
    - fixed in #453
- [x] #455 
    - fixed in #480 
- [x] #456 
    - fixed in #481 
- [x] #457 
    - fixed in #477 

### `frost-ed25519`

_No findings_

### `frost-ed448`

- [x] NCC-E008263-72Y: Ed448 Base Field Incorrect Negation
    - Fixed in https://github.com/crate-crypto/Ed448-Goldilocks/issues/28 by https://github.com/crate-crypto/Ed448-Goldilocks/pull/29, and
    - in https://github.com/mit-plv/fiat-crypto/issues/1620 by https://github.com/mit-plv/fiat-crypto/pull/1623
- [x] NCC-E008263-T3P: Potential Timing Attacks in Ed448
Implementation
    - Fixed in https://github.com/crate-crypto/Ed448-Goldilocks/issues/30 by https://github.com/crate-crypto/Ed448-Goldilocks/pull/31
- [x] NCC-E008263-HGL: Lack of Zeroization in Ed448 Scalar Inversion
    - Fixed in https://github.com/crate-crypto/Ed448-Goldilocks/issues/32 by https://github.com/crate-crypto/Ed448-Goldilocks/pull/33

### `frost-p256`

_No findings_

### `frost-secp256k1`

_No findings_

### `frost-ristretto255`

_No findings_

### Optional Tasks

Other miscellaneous remarks that are not considered security vulnerabilities. Fixing these could increase code quality.

- General Notes on `frost-core`
    - [x] #458
        - fixed in #482 
    - [x] #459 
        - fixed in #483     
    - [x] #460 
        - fixed by #481 
    - [x] #461 
        - fixed by #494      
    - [x] #462 
        - fixed by #484  
    - [x] #463 
        - fixed in #485
    - [x] #464 
        - fixed in #485    
    - [x] #465
        - fixed in #496 
- Notes on RedDSA
    - No Action: We acknowledge the comment and have an explanation for the discrepancies.
- Observations on Batch Verification
    - [x] #444 
    - [x] #445 
        - fixed in #487
    - [x] #446
        - fixed in #487    
- Notes on the Different FROST Versions
    - [x] #447
        - fixed in #488 
    - [x] Update `CONTEXT_STRING` values to match latest spec 
        - fixed in #438
-  Notes on the IETF Draft
    - [x] https://github.com/cfrg/draft-irtf-cfrg-frost/issues/445 - fixed by https://github.com/cfrg/draft-irtf-cfrg-frost/issues/448
    - [x] https://github.com/cfrg/draft-irtf-cfrg-frost/issues/446 - fixed by  https://github.com/cfrg/draft-irtf-cfrg-frost/issues/447
    - [x] https://github.com/cfrg/draft-irtf-cfrg-frost/issues/453  - fixed by  https://github.com/cfrg/draft-irtf-cfrg-frost/issues/456   
- Minor Documentation Notes on the Source Code 
    - [x] #448
        - fixed in #489 
        - There's one outstanding `TODO` in the code which is still waiting for `div_ceil` to make it into stable rust
- Notes on the FROST Book 
    - [x] #466
        - fixed in #491

**Comment by mpguerra** [comment]
All done here!
