### ISSUE TITLE
Interop testing over Ristretto-Sha512

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#8]
This Epic will track the work required to implement cfrg/draft-irtf-cfrg-frost#22

## Tasks

- [ ] Review code for the various implementations to check implementation is spec conformant 
    - [ ] [`frost-dalek`](https://github.com/isislovecrusft/frost-dalek)
    - [ ] [`frost-ristretto255`](https://github.com/ZcashFoundation/frost/tree/main/frost-ristretto255) 
- [x] Generate Test vectors
    - [x] Define how test vectors are generated in spec
- [ ] Interop testing with [`frost-dalek`](https://github.com/isislovecrusft/frost-dalek)
- [ ] Interop testing with [`frost-ristretto255`](https://github.com/ZcashFoundation/frost/tree/main/frost-ristretto255) 
- [ ] Ensure implementations conform to spec
